# Generated by Django 4.2.30 on 2026-08-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0003_tracksection_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status Change'), ('escalation', 'Escalation'), ('login', 'Login'), ('logout', 'Logout'), ('system', 'System')], help_text='Category of the audited event.', max_length=20),
        ),
    ]
