# Generated by Django 6.1 on 2026-08-22 13:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0004_alter_auditlog_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalReadinessCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once on INSERT).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (updated on every save).')),
                ('case_code', models.CharField(help_text="Unique operational readiness case code, e.g. 'ORC-2026-001'.", max_length=30, unique=True)),
                ('case_type', models.CharField(choices=[('track_reopening', 'Track Re-Opening & Speed Clearance'), ('route_departure', 'Train Route Departure Clearance')], default='track_reopening', max_length=30)),
                ('train_number', models.CharField(blank=True, default='', help_text="Train number/name for departure clearance cases, e.g. '12951 Rajdhani Express'.", max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('cleared_speed_kmph', models.PositiveIntegerField(default=0, help_text='Permitted speed after readiness clearance (e.g. 130 km/h, 30 km/h, 0 km/h).')),
                ('is_overridden', models.BooleanField(default=False, help_text='True if an operational override was recorded.')),
                ('workflow_status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('field_verification', 'Field Verification'), ('awaiting_decision', 'Awaiting Decision'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('readiness_decision', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('conditionally_ready', 'Conditionally Ready'), ('not_ready', 'Not Ready')], default='pending', max_length=20)),
                ('isolation_state', models.CharField(choices=[('unknown', 'Unknown'), ('isolated', 'Isolated'), ('partially_isolated', 'Partially Isolated'), ('restored', 'Restored')], default='unknown', max_length=20)),
                ('isolated_at', models.DateTimeField(blank=True, help_text='When the track/asset was isolated.', null=True)),
                ('isolated_by', models.CharField(blank=True, default='', max_length=150)),
                ('isolation_reference', models.CharField(blank=True, default='', help_text='Reference number or authority for the isolation.', max_length=100)),
                ('restoration_target_at', models.DateTimeField(blank=True, help_text='Target date/time for restoring operational state.', null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('restored_by', models.CharField(blank=True, default='', max_length=150)),
                ('sensor_window_start', models.DateTimeField(blank=True, help_text='Start of the sensor observation window used for readiness metrics.', null=True)),
                ('sensor_window_end', models.DateTimeField(blank=True, help_text='End of the sensor observation window used for readiness metrics.', null=True)),
                ('sensor_metrics', models.JSONField(blank=True, default=dict, help_text="Aggregated sensor metrics supporting the readiness decision. Example: {'vibration_rms_avg': 2.1, 'temperature_max': 61.4}.")),
                ('readiness_score', models.DecimalField(blank=True, decimal_places=2, help_text='Composite readiness score, 0.00 (not ready) to 100.00 (ready).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('decision_taken_by', models.CharField(blank=True, default='', max_length=150)),
                ('decision_taken_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reference', models.CharField(blank=True, default='', max_length=100)),
                ('decision_conditions', models.TextField(blank=True, default='', help_text='Conditions attached to a conditional readiness decision.')),
                ('decision_notes', models.TextField(blank=True, default='')),
                ('valid_until', models.DateField(blank=True, help_text='Expiry date of the readiness decision, if applicable.', null=True)),
                ('alert', models.ForeignKey(blank=True, help_text='Related alert, if the case originated from an alert condition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readiness_cases', to='railway.alert')),
                ('asset', models.ForeignKey(blank=True, help_text='Optional asset scoped by this readiness case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readiness_cases', to='railway.asset')),
                ('assigned_team', models.ForeignKey(blank=True, help_text='Field team responsible for verification and sign-off.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readiness_cases', to='railway.maintenanceteam')),
                ('ticket', models.ForeignKey(blank=True, help_text='Maintenance ticket that triggered this readiness assessment, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readiness_cases', to='railway.ticket')),
                ('track_section', models.ForeignKey(blank=True, help_text='Track section being assessed. PROTECT preserves readiness history.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='readiness_cases', to='railway.tracksection')),
            ],
            options={
                'verbose_name': 'Operational Readiness Case',
                'verbose_name_plural': 'Operational Readiness Cases',
                'db_table': 'rakshak_operational_readiness_case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadinessChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once on INSERT).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (updated on every save).')),
                ('sequence', models.PositiveIntegerField(help_text='Display/ordering sequence within the checklist.')),
                ('item_code', models.CharField(blank=True, default='', help_text="Optional stable checklist item code, e.g. 'TRK-CLEAR-01'.", max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('track', 'Track'), ('signal', 'Signal'), ('ohe', 'OHE'), ('bridge', 'Bridge'), ('civil', 'Civil'), ('safety', 'Safety'), ('documentation', 'Documentation'), ('other', 'Other')], default='other', max_length=15)),
                ('is_required', models.BooleanField(default=True, help_text='False for informational or optional checklist entries.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable'), ('requires_action', 'Requires Action')], default='pending', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Weight used when calculating readiness score.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('signed_off_by', models.CharField(blank=True, default='', max_length=150)),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('sign_off_designation', models.CharField(blank=True, default='', max_length=100)),
                ('sign_off_comments', models.TextField(blank=True, default='')),
                ('signed_off_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude where the sign-off was recorded.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('signed_off_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude where the sign-off was recorded.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('evidence', models.JSONField(blank=True, default=dict, help_text="Evidence metadata such as photos, documents, or measurements. Example: {'photos': ['s3://bucket/a.jpg'], 'notes': 'torque checked'}.")),
                ('requires_followup', models.BooleanField(default=False)),
                ('followup_notes', models.TextField(blank=True, default='')),
                ('case', models.ForeignKey(help_text='Parent readiness case. Checklist items belong to one case.', on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='railway.operationalreadinesscase')),
            ],
            options={
                'verbose_name': 'Readiness Checklist Item',
                'verbose_name_plural': 'Readiness Checklist Items',
                'db_table': 'rakshak_readiness_checklist_item',
                'ordering': ['case', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ReadinessAuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once on INSERT).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (updated on every save).')),
                ('record_type', models.CharField(choices=[('status_change', 'Status Change'), ('isolation_state', 'Isolation State'), ('checklist_signoff', 'Checklist Sign-off'), ('sensor_metrics', 'Sensor Metrics'), ('decision', 'Decision'), ('comment', 'Comment'), ('system', 'System')], max_length=20)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('ml_pipeline', 'ML Pipeline'), ('field_team', 'Field Team'), ('sensor', 'Sensor')], default='user', max_length=20)),
                ('actor_identifier', models.CharField(blank=True, default='', max_length=150)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the readiness event occurred.')),
                ('previous_state', models.JSONField(blank=True, default=dict, help_text='Snapshot of relevant case fields before the event.')),
                ('new_state', models.JSONField(blank=True, default=dict, help_text='Snapshot of relevant case fields after the event.')),
                ('sensor_metrics', models.JSONField(blank=True, default=dict, help_text='Sensor metric snapshot attached to this record, if applicable.')),
                ('decision', models.CharField(blank=True, choices=[('pending', 'Pending'), ('ready', 'Ready'), ('conditionally_ready', 'Conditionally Ready'), ('not_ready', 'Not Ready')], help_text='Decision value for decision-type records.', max_length=20, null=True)),
                ('decision_reference', models.CharField(blank=True, default='', max_length=100)),
                ('decision_summary', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('case', models.ForeignKey(help_text='Readiness case being audited. PROTECT preserves decision records.', on_delete=django.db.models.deletion.PROTECT, related_name='audit_records', to='railway.operationalreadinesscase')),
                ('checklist_item', models.ForeignKey(blank=True, help_text='Checklist item associated with this record, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to='railway.readinesschecklistitem')),
            ],
            options={
                'verbose_name': 'Readiness Audit Record',
                'verbose_name_plural': 'Readiness Audit Records',
                'db_table': 'rakshak_readiness_audit_record',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='operationalreadinesscase',
            index=models.Index(fields=['workflow_status'], name='idx_orc_status'),
        ),
        migrations.AddIndex(
            model_name='operationalreadinesscase',
            index=models.Index(fields=['readiness_decision'], name='idx_orc_decision'),
        ),
        migrations.AddIndex(
            model_name='operationalreadinesscase',
            index=models.Index(fields=['track_section', 'workflow_status'], name='idx_orc_ts_status'),
        ),
        migrations.AddIndex(
            model_name='operationalreadinesscase',
            index=models.Index(fields=['isolation_state'], name='idx_orc_isolation'),
        ),
        migrations.AddIndex(
            model_name='readinesschecklistitem',
            index=models.Index(fields=['case', 'status'], name='idx_rcl_case_status'),
        ),
        migrations.AddIndex(
            model_name='readinesschecklistitem',
            index=models.Index(fields=['signed_off_at'], name='idx_rcl_signed_at'),
        ),
        migrations.AddConstraint(
            model_name='readinesschecklistitem',
            constraint=models.UniqueConstraint(fields=('case', 'sequence'), name='uniq_rcl_case_seq'),
        ),
        migrations.AddIndex(
            model_name='readinessauditrecord',
            index=models.Index(fields=['case', 'occurred_at'], name='idx_rar_case_time'),
        ),
        migrations.AddIndex(
            model_name='readinessauditrecord',
            index=models.Index(fields=['record_type'], name='idx_rar_type'),
        ),
        migrations.AddIndex(
            model_name='readinessauditrecord',
            index=models.Index(fields=['decision'], name='idx_rar_decision'),
        ),
    ]
