# Generated by Django 6.1 on 2026-08-22 18:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('railway', '0005_operationalreadinesscase_readinesschecklistitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPatrolReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once on INSERT).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (updated on every save).')),
                ('patrol_code', models.CharField(help_text="Unique patrol code, e.g. 'PTR-2026-0001'.", max_length=30, unique=True)),
                ('patrol_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patrol_completed_at', models.DateTimeField(blank=True, null=True)),
                ('worker_overall_score', models.DecimalField(blank=True, decimal_places=2, help_text='Worker inspection score (0-100), avg of 8 category ratings × 20.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('iot_overall_score', models.DecimalField(blank=True, decimal_places=2, help_text='IoT health score (0-100), derived from ML anomaly prediction.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('iot_readings', models.JSONField(blank=True, default=list, help_text='16-reading IoT sensor window generated post-inspection.')),
                ('iot_generator_backend', models.CharField(blank=True, default='', help_text='Which backend generated IoT data: gemini, anthropic, physics_iot_rng, etc.', max_length=30)),
                ('iot_prediction', models.JSONField(blank=True, default=dict, help_text='Full ML prediction result from the PredictionService pipeline.')),
                ('iot_scenario_flavour', models.CharField(blank=True, default='', max_length=100)),
                ('worker_weight', models.DecimalField(decimal_places=2, default=Decimal('0.60'), help_text='Weight given to worker score in composite. Default 0.60 (60%).', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('iot_weight', models.DecimalField(decimal_places=2, default=Decimal('0.40'), help_text='Weight given to IoT score in composite. Default 0.40 (40%).', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('composite_score', models.DecimalField(blank=True, decimal_places=2, help_text='Weighted composite: (worker_weight × worker_score) + (iot_weight × iot_score).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('conflict_detected', models.BooleanField(default=False, help_text='True when worker score and IoT score disagree by > 30 points.')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Worker Report Submitted'), ('iot_generated', 'IoT Data Generated'), ('under_review', 'Under Admin Review'), ('decided', 'Decision Made')], default='in_progress', max_length=20)),
                ('admin_decision', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared for Operations'), ('restricted', 'Speed Restriction Applied'), ('blocked', 'Route Blocked')], default='pending', max_length=20)),
                ('admin_decision_by', models.CharField(blank=True, default='', max_length=150)),
                ('admin_decision_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('admin_speed_restriction', models.PositiveIntegerField(default=0, help_text='Speed restriction applied by admin (km/h). 0 = no restriction.')),
                ('track_section', models.ForeignKey(help_text='Track section inspected (Station A → Station B).', on_delete=django.db.models.deletion.PROTECT, related_name='patrol_reports', to='railway.tracksection')),
                ('worker', models.ForeignKey(help_text='Worker who performed the patrol.', on_delete=django.db.models.deletion.PROTECT, related_name='patrol_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worker Patrol Report',
                'verbose_name_plural': 'Worker Patrol Reports',
                'db_table': 'rakshak_worker_patrol_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatrolCategoryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once on INSERT).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (updated on every save).')),
                ('category', models.CharField(choices=[('rail_condition', 'Rail Condition'), ('track_geometry', 'Track Geometry'), ('sleepers_fastenings', 'Sleepers & Fastenings'), ('ballast_condition', 'Ballast Condition'), ('drainage', 'Drainage'), ('points_crossings', 'Points & Crossings'), ('level_crossings', 'Level Crossings'), ('formation_earthwork', 'Formation & Earthwork')], max_length=30)),
                ('rating', models.PositiveIntegerField(help_text='1=Critical, 2=Poor, 3=Fair, 4=Good, 5=Excellent', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, default='', help_text="Worker's observation notes for this category.")),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ratings', to='patrol.workerpatrolreport')),
            ],
            options={
                'verbose_name': 'Patrol Category Rating',
                'verbose_name_plural': 'Patrol Category Ratings',
                'db_table': 'rakshak_patrol_category_rating',
                'ordering': ['patrol', 'category'],
            },
        ),
        migrations.AddIndex(
            model_name='workerpatrolreport',
            index=models.Index(fields=['status'], name='idx_patrol_status'),
        ),
        migrations.AddIndex(
            model_name='workerpatrolreport',
            index=models.Index(fields=['worker', 'status'], name='idx_patrol_worker_st'),
        ),
        migrations.AddIndex(
            model_name='workerpatrolreport',
            index=models.Index(fields=['admin_decision'], name='idx_patrol_decision'),
        ),
        migrations.AddConstraint(
            model_name='patrolcategoryrating',
            constraint=models.UniqueConstraint(fields=('patrol', 'category'), name='uniq_patrol_category'),
        ),
    ]
